from __future__ import annotations

from .errors import EmbeddingError, SemanticCacheUsageError, ValkeyCommandError
from .normalizer import (
    BinaryNormalizer,
    BinaryRef,
    NormalizerConfig,
    compose_normalizer,
    default_normalizer,
    fetch_and_hash,
    hash_base64,
    hash_bytes,
    hash_url,
    passthrough,
)
from .semantic_cache import SemanticCache
from .types import (
    CacheCheckOptions,
    ConfigRefreshOptions,
    CacheCheckResult,
    CacheConfidence,
    CacheStats,
    CacheStoreOptions,
    DiscoveryOptions,
    EmbedFn,
    EmbeddingCacheOptions,
    IndexInfo,
    InvalidateResult,
    JudgeOptions,
    ModelCost,
    NearestMiss,
    RerankOptions,
    SemanticCacheOptions,
    TelemetryOptions,
    ThresholdEffectivenessResult,
)
from .utils import (
    BinaryBlock,
    ContentBlock,
    ReasoningBlock,
    TextBlock,
    ToolCallBlock,
    ToolResultBlock,
    decode_float32,
    encode_float32,
    escape_tag,
    extract_binary_refs,
    extract_text,
    parse_ft_search_response,
    sha256,
)

__all__ = [
    "SemanticCache",
    "SemanticCacheOptions",
    "ConfigRefreshOptions",
    "DiscoveryOptions",
    "CacheCheckOptions",
    "CacheStoreOptions",
    "CacheCheckResult",
    "CacheConfidence",
    "CacheStats",
    "IndexInfo",
    "InvalidateResult",
    "JudgeOptions",
    "ModelCost",
    "NearestMiss",
    "RerankOptions",
    "EmbeddingCacheOptions",
    "TelemetryOptions",
    "ThresholdEffectivenessResult",
    "EmbedFn",
    # errors
    "SemanticCacheUsageError",
    "EmbeddingError",
    "ValkeyCommandError",
    # normalizer
    "BinaryNormalizer",
    "BinaryRef",
    "NormalizerConfig",
    "compose_normalizer",
    "default_normalizer",
    "hash_base64",
    "hash_bytes",
    "hash_url",
    "fetch_and_hash",
    "passthrough",
    # content blocks
    "ContentBlock",
    "TextBlock",
    "BinaryBlock",
    "ToolCallBlock",
    "ToolResultBlock",
    "ReasoningBlock",
    # utils
    "encode_float32",
    "decode_float32",
    "escape_tag",
    "extract_text",
    "extract_binary_refs",
    "parse_ft_search_response",
    "sha256",
]
